// Company Information
export const COMPANY_INFO = {
  name: 'Stoneo India', // 'Stoneo India',
  description: 'Premium Stone Supplier in Kishangarh, Rajasthan', // 'Premium Granite Supplier in Kishangarh, Rajasthan',
  // tagline: 'Quality Granite for Every Project', // 'Quality Granite for Every Project',
  address: 'Makrana Rd, Kali Dungri, Kishangarh, Rajasthan 305801', // 'Kali Dungri, Khatoli, Kishangarh, Rajasthan 305801',
  phone: '1234567890', // '9256901351',
  email: 'demo@example.com', // 'infostoneo@gmail.com',
  businessHours: '9:00 AM - 5:00 PM', // '10:00 AM - 7:00 PM',
  established: '2024', // '2008',
};

export const GRANITE_TYPES = [
  {
    id: 1,
    name: 'Black Galaxy Granite',
    image: '/granite_images/Black Galaxy Granite.webp',
    description: 'Premium quality black granite with fine grain texture. Perfect for countertops and flooring.',
    pricePerSqft: 45,
    features: ['Highly durable', 'Scratch resistant', 'Low maintenance', 'Heat resistant'],
  },
  {
    id: 2,
    name: 'Absolute Black Granite',
    image: '/granite_images/Absolute Black Granite.webp',
    description: 'Elegant Black granite with subtle patterns. Ideal for premium interiors.',
    pricePerSqft: 55,
    features: ['Elegant appearance', 'Weather resistant', 'Polished finish', 'Long lasting'],
  },
  {
    id: 3,
    name: 'Tan Brown Granite',
    image: '/granite_images/Tan Brown Granite.jpg',
    description: 'Natural tan brown granite with earthy tones. Great for creating contemporary spaces.',
    pricePerSqft: 50,
    features: ['Unique patterns', 'Eco-friendly', 'Versatile design', 'Premium quality'],
  },
  {
    id: 4,
    name: 'Rosy Pink Granite',
    image: '/granite_images/Rosy Pink Granite.webp',
    description: 'Vibrant multicolor granite combining various hues. Perfect for statement designs.',
    pricePerSqft: 60,
    features: ['Bold appearance', 'Premium finish', 'Unique patterns', 'High demand'],
  },
  {
    id: 5,
    name: 'Jhansi Red Granite',
    image: '/granite_images/Jhansi Red Granite.webp',
    description: 'Rich red granite with striking appearance. Excellent for both residential and commercial use.',
    pricePerSqft: 48,
    features: ['Bold color', 'Durable', 'Versatile use', 'Easy maintenance'],
  },
  {
    id: 6,
    name: 'Kashmir White Granite',
    image: '/granite_images/Kashmir White Granite.jpg',
    description: 'Soft pink granite with elegant aesthetics. Popular for modern and classic designs.',
    pricePerSqft: 52,
    features: ['Soft tones', 'Elegant', 'Residential friendly', 'Premium quality'],
  },
];

// Projects Gallery
export const PROJECTS = [
  {
    id: 1,
    title: 'The Oberoi Grand Atrium & Lobby',
    location: 'Udaipur, Rajasthan',
    category: 'Hospitality',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    description: 'Monolithic Statuario Marble bookmatched flooring across a 14,500 sq.ft hotel atrium with mirror-polish calibration.',
    stoneUsed: 'Italian Statuario Marble',
    graniteType: 'Italian Statuario Marble',
    area: '14,500 Sq.Ft',
    year: '2025',
    architect: 'Studio Vistara'
  },
  {
    id: 2,
    title: 'Taj Diplomatic Presidential Suite',
    location: 'New Delhi',
    category: 'Residential',
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    description: 'Ultra-precision honed Absolute Black Granite flooring and bespoke floating vanity countertops with gold inlay borders.',
    stoneUsed: 'Absolute Black Granite',
    graniteType: 'Absolute Black Granite',
    area: '6,200 Sq.Ft',
    year: '2025',
    architect: 'Lutyens Design Studio'
  },
  {
    id: 3,
    title: 'The Sukhvilas Colonnade Facade',
    location: 'Chandigarh',
    category: 'Architectural',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4ea0d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    description: 'Seaward-resistant Alaska White Granite exterior cladding and hand-carved architectural pillars with ±0.5mm joint tolerance.',
    stoneUsed: 'Alaska White Granite',
    graniteType: 'Alaska White Granite',
    area: '18,000 Sq.Ft',
    year: '2024',
    architect: 'Architrope Atelier'
  },
  {
    id: 4,
    title: 'JW Marriott Backlit Lounge Bar',
    location: 'Mumbai, Maharashtra',
    category: 'Hospitality',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    description: 'Custom backlit Blue Agate semi-precious stone countertops and bar fascia with integrated LED diffusion technology.',
    stoneUsed: 'Royal Blue Agate Gemstone',
    graniteType: 'Royal Blue Agate Gemstone',
    area: '3,800 Sq.Ft',
    year: '2025',
    architect: 'Aura Luxury Interiors'
  },
  {
    id: 5,
    title: 'Private Royal Sanctuary Villa',
    location: 'Jaipur, Rajasthan',
    category: 'Residential',
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    description: 'Calacatta Gold Marble master suite walls, cantilevered staircase treads, and bespoke water-jet medallion foyer.',
    stoneUsed: 'Calacatta Gold Marble',
    graniteType: 'Calacatta Gold Marble',
    area: '9,500 Sq.Ft',
    year: '2024',
    architect: 'Royal Heritage Architects'
  },
  {
    id: 6,
    title: 'Cyber City Architectural Plaza',
    location: 'Gurugram, NCR',
    category: 'Commercial',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    description: 'Flamed and lapotra finish Steel Grey Granite outdoor walkways, water feature cladding, and amphitheater seating.',
    stoneUsed: 'Steel Grey Granite',
    graniteType: 'Steel Grey Granite',
    area: '35,000 Sq.Ft',
    year: '2024',
    architect: 'UrbanScape India'
  },
];

// FAQs
export const FAQS = [
  {
    id: 1,
    question: 'What is the difference between granite and marble?',
    answer: 'Granite is a natural igneous rock that is harder and more durable than marble. It is highly resistant to scratches, heat, and stains, making it ideal for countertops and high-traffic areas. Marble is softer and more porous, perfect for decorative applications.',
  },
  {
    id: 2,
    question: 'How do I maintain granite surfaces?',
    answer: 'Granite requires minimal maintenance. Wipe spills immediately, use pH-neutral cleaners, avoid acidic substances, and reseal annually. With proper care, granite lasts for decades without significant wear.',
  },
  {
    id: 3,
    question: 'Where is Stoneo India located?',
    answer: 'Stoneo India is located in Kali Dungri, Khatoli, Kishangarh, Rajasthan. We have direct access to premium granite quarries and offer competitive pricing due to our location in the heart of India\'s stone industry.',
  },
  {
    id: 4,
    question: 'Do you provide installation services?',
    answer: 'Yes, we provide both granite supply and professional installation services. Our experienced team ensures flawless installation with proper sealing and finishing.',
  },
  {
    id: 5,
    question: 'What is the typical cost per square foot?',
    answer: 'Prices range from $45-$60 per square foot depending on granite type and quality. Premium varieties and custom finishes may cost more. We offer competitive bulk pricing for large projects.',
  },
  {
    id: 6,
    question: 'Can I see samples before ordering?',
    answer: 'Absolutely! We have a well-stocked showroom with various granite samples. Customers can visit anytime during business hours (10 AM - 7 PM) to view and feel the stones.',
  },
  {
    id: 7,
    question: 'Do you export internationally?',
    answer: 'Yes, we have experience with international exports. We handle customs, shipping, and documentation for bulk orders to various countries.',
  },
  {
    id: 8,
    question: 'What is the warranty on granite?',
    answer: 'Granite naturally lasts for decades. We offer a 1-year warranty on installation and workmanship, ensuring quality and customer satisfaction.',
  },
];

// Per-product RGB: dominant color from each stone. texture: 0=smooth/uniform, 100=heavily speckled
export const CSV_PRODUCTS = [
  // Black Granites
  { name: 'Absolute Black Granite', image: '/granite_images/Absolute Black Granite.webp', price: 52, category: 'Black', material: 'Granite', rgb: [18, 18, 18], texture: 5 },
  { name: 'Black Galaxy Granite', image: '/granite_images/Black Galaxy Granite.webp', price: 52, category: 'Black', material: 'Granite', rgb: [22, 22, 35], texture: 55 },
  { name: 'Black Forest Granite', image: '/granite_images/Black Forest Granite.webp', price: 52, category: 'Black', material: 'Granite', rgb: [30, 28, 24], texture: 30 },
  { name: 'Black Pearl Granite', image: '/granite_images/Black Pearl Granite.jpg', price: 52, category: 'Black', material: 'Granite', rgb: [24, 28, 40], texture: 65 },
  { name: 'Ash Black Granite', image: '/granite_images/Ash Black Granite.jpg', price: 52, category: 'Black', material: 'Granite', rgb: [50, 50, 50], texture: 20 },
  { name: 'Coin Black Granite', image: '/granite_images/Coin Black Granite.jpg', price: 52, category: 'Black', material: 'Granite', rgb: [38, 36, 35], texture: 25 },
  { name: 'Fusion Black Granite', image: '/granite_images/Fusion Black Granite.webp', price: 52, category: 'Black', material: 'Granite', rgb: [42, 38, 32], texture: 40 },
  { name: 'Impala Black Granite', image: '/granite_images/Impala Black Granite.webp', price: 52, category: 'Black', material: 'Granite', rgb: [28, 28, 28], texture: 10 },
  { name: 'Titanium Black Granite', image: '/granite_images/Titanium Black Granite.webp', price: 52, category: 'Black', material: 'Granite', rgb: [20, 20, 22], texture: 15 },

  // White Granites
  { name: 'Classic White Granite', image: '/granite_images/Classic White Granite.jpg', price: 52, category: 'White', material: 'Granite', rgb: [222, 218, 212], texture: 45 },
  { name: 'Andromeda White Granite', image: '/granite_images/Andromeda White Granite.jpg', price: 52, category: 'White', material: 'Granite', rgb: [190, 185, 180], texture: 70 },
  { name: 'Alaska White Granite', image: '/granite_images/Alaska White Granite.webp', price: 52, category: 'White', material: 'Granite', rgb: [210, 205, 195], texture: 55 },
  { name: 'Azul White Granite', image: '/granite_images/Azul White Granite.jpg', price: 52, category: 'White', material: 'Granite', rgb: [195, 200, 215], texture: 60 },
  { name: 'Colonial White Granite', image: '/granite_images/Colonial White Granite.webp', price: 52, category: 'White', material: 'Granite', rgb: [228, 222, 210], texture: 35 },
  { name: 'Kashmir White Granite', image: '/granite_images/Kashmir White Granite.jpg', price: 52, category: 'White', material: 'Granite', rgb: [200, 192, 183], texture: 50 },
  { name: 'Moon White Granite', image: '/granite_images/Moon White Granite.webp', price: 52, category: 'White', material: 'Granite', rgb: [235, 230, 225], texture: 25 },

  // Gold Granites
  { name: 'Alaska Gold Granite', image: '/granite_images/Alaska Gold Granite.webp', price: 52, category: 'Gold', material: 'Granite', rgb: [185, 155, 80], texture: 60 },
  { name: 'Imperial Gold Granite', image: '/granite_images/Imperial Gold Granite.webp', price: 52, category: 'Gold', material: 'Granite', rgb: [175, 145, 70], texture: 70 },
  { name: 'Ghibli Gold Granite', image: '/granite_images/Ghibli Gold Granite.jpg', price: 52, category: 'Gold', material: 'Granite', rgb: [195, 168, 90], texture: 55 },
  { name: 'Desert Gold Granite', image: '/granite_images/Desert Gold Granite.webp', price: 52, category: 'Gold', material: 'Granite', rgb: [205, 178, 100], texture: 45 },

  // Blue Granites
  { name: 'Blue Dunes Granite', image: '/granite_images/Blue Dunes Granite.jpg', price: 52, category: 'Blue', material: 'Granite', rgb: [100, 118, 148], texture: 50 },
  { name: 'Blue Pearl Granite', image: '/granite_images/Blue Pearl Granite.jpg', price: 52, category: 'Blue', material: 'Granite', rgb: [58, 78, 140], texture: 65 },
  { name: 'Flash Blue Granite', image: '/granite_images/Flash Blue Granite.webp', price: 52, category: 'Blue', material: 'Granite', rgb: [48, 68, 128], texture: 75 },
  { name: 'Amadeus Blue Granite', image: '/granite_images/Amadeus Blue Granite.jpg', price: 52, category: 'Blue', material: 'Granite', rgb: [82, 108, 155], texture: 55 },

  // Green Granites
  { name: 'Nosra Green Granite', image: '/granite_images/Nosra Green Granite.jpg', price: 52, category: 'Green', material: 'Granite', rgb: [58, 108, 68], texture: 50 },
  { name: 'Desert Green Granite', image: '/granite_images/Desert Green Granite.webp', price: 52, category: 'Green', material: 'Granite', rgb: [78, 118, 72], texture: 40 },
  { name: 'Hassan Green Granite', image: '/granite_images/Hassan Green Granite.jpg', price: 52, category: 'Green', material: 'Granite', rgb: [52, 98, 60], texture: 55 },
  { name: 'Apple Green Granite', image: '/granite_images/Apple Green Granite.webp', price: 52, category: 'Green', material: 'Granite', rgb: [102, 148, 88], texture: 35 },

  // Brown Granites
  { name: 'Tan Brown Granite', image: '/granite_images/Tan Brown Granite.jpg', price: 52, category: 'Brown', material: 'Granite', rgb: [148, 98, 68], texture: 65 },
  { name: 'Coffee Brown Granite', image: '/granite_images/Coffee Brown Granite.webp', price: 52, category: 'Brown', material: 'Granite', rgb: [98, 62, 42], texture: 45 },
  { name: 'Desert Brown Granite', image: '/granite_images/Desert Brown Granite.webp', price: 52, category: 'Brown', material: 'Granite', rgb: [162, 132, 95], texture: 40 },

  // Red Granites
  { name: 'Jhansi Red Granite', image: '/granite_images/Jhansi Red Granite.webp', price: 52, category: 'Red', material: 'Granite', rgb: [152, 48, 48], texture: 55 },
  { name: 'Lakha Red Granite', image: '/granite_images/Lakha Red Granite.webp', price: 52, category: 'Red', material: 'Granite', rgb: [172, 58, 55], texture: 60 },
  { name: 'New Imperiala Red Granite', image: '/granite_images/New Imperiala Red Granite.jpg', price: 52, category: 'Red', material: 'Granite', rgb: [138, 42, 42], texture: 50 },

  // --- INDIAN MARBLES ---
  { name: 'Makrana White Marble', image: '/indian_marble_images/Makrana White Marble.jpg', price: 50, category: 'White', material: 'Marble', rgb: [240, 240, 240], texture: 5 },
  { name: 'Ambaji White Marble', image: '/indian_marble_images/Ambaji White Marble.jpg', price: 45, category: 'White', material: 'Marble', rgb: [230, 235, 230], texture: 10 },
  { name: 'Udaipur Green Marble', image: '/indian_marble_images/Udaipur Green Marble.jpg', price: 40, category: 'Green', material: 'Marble', rgb: [45, 95, 55], texture: 25 },
  { name: 'Banswara Purple Marble', image: '/indian_marble_images/Banswara Purple Marble.jpg', price: 48, category: 'Multicolor', material: 'Marble', rgb: [160, 140, 170], texture: 30 },
  { name: 'Katni Marble', image: '/indian_marble_images/Katni Marble.jpg', price: 55, category: 'Cream', material: 'Marble', rgb: [210, 200, 180], texture: 15 },
  { name: 'Dungri Marble', image: '/indian_marble_images/Dungri Marble.jpg', price: 42, category: 'White', material: 'Marble', rgb: [225, 225, 225], texture: 12 },
  { name: 'Agaria White Marble', image: '/indian_marble_images/Agaria White Marble.jpg', price: 44, category: 'White', material: 'Marble', rgb: [235, 235, 235], texture: 8 },
  { name: 'Onyx White Marble', image: '/indian_marble_images/Onyx White Marble.jpg', price: 90, category: 'White', material: 'Marble', rgb: [250, 250, 245], texture: 5 },

  // --- ITALIAN MARBLES ---
  { name: 'Statuario Marble', image: '/indian_marble_images/Statuario Marble.jpg', price: 150, category: 'White', material: 'Marble', rgb: [245, 245, 245], texture: 15 },
  { name: 'Calacatta Gold Marble', image: '/indian_marble_images/Calacatta Gold Marble.jpg', price: 180, category: 'White', material: 'Marble', rgb: [242, 238, 230], texture: 25 },
  { name: 'Botticino Marble', image: '/indian_marble_images/Botticino Marble.jpg', price: 95, category: 'Cream', material: 'Marble', rgb: [225, 215, 195], texture: 12 },
  { name: 'Perlato Sicilia Marble', image: '/indian_marble_images/Perlato Sicilia Marble.jpg', price: 85, category: 'Cream', material: 'Marble', rgb: [230, 220, 200], texture: 18 },
  { name: 'Rosso Levanto Marble', image: '/indian_marble_images/Rosso Levanto Marble.jpg', price: 110, category: 'Red', material: 'Marble', rgb: [120, 40, 45], texture: 30 },
  { name: 'Arabescato Marble', image: '/indian_marble_images/Arabescato Marble.jpg', price: 140, category: 'White', material: 'Marble', rgb: [238, 238, 238], texture: 20 },
  { name: 'Bianco Lasa Marble', image: '/indian_marble_images/Bianco Lasa Marble.jpg', price: 160, category: 'White', material: 'Marble', rgb: [248, 248, 248], texture: 10 },
  { name: 'Giallo Siena Marble', image: '/indian_marble_images/Giallo Siena Marble.jpg', price: 130, category: 'Yellow', material: 'Marble', rgb: [215, 185, 90], texture: 25 },
  { name: 'Portoro Marble', image: '/indian_marble_images/Portoro Marble.jpg', price: 190, category: 'Black', material: 'Marble', rgb: [30, 28, 25], texture: 35 },
  { name: 'Carrara White Marble', image: '/indian_marble_images/Carrara White Marble.jpg', price: 60, category: 'White', material: 'Marble', rgb: [232, 228, 222], texture: 10 },
  { name: 'Nero Marquina Marble', image: '/indian_marble_images/Nero Marquina Marble.jpg', price: 65, category: 'Black', material: 'Marble', rgb: [15, 15, 15], texture: 8 },

  // --- SANDSTONES ---
  { name: 'Teakwood Sandstone', image: '/paving_and_stones/Teakwood Sandstone.jpg', price: 40, category: 'Brown', material: 'Sandstone', rgb: [168, 128, 90], texture: 30 },
  { name: 'Agra Red Sandstone', image: '/paving_and_stones/Agra Red Sandstone.jpg', price: 42, category: 'Red', material: 'Sandstone', rgb: [175, 82, 68], texture: 25 },
  { name: 'Dholpur Beige Sandstone', image: '/paving_and_stones/Dholpur Beige Sandstone.jpg', price: 38, category: 'Cream', material: 'Sandstone', rgb: [210, 200, 175], texture: 15 },
  { name: 'Bansi Paharpur Pink', image: '/other/Bansi Paharpur Pink.jpg', price: 45, category: 'Pink', material: 'Sandstone', rgb: [195, 140, 140], texture: 20 },
  { name: 'Modak Sandstone', image: '/paving_and_stones/Modak Sandstone.jpg', price: 44, category: 'Pink', material: 'Sandstone', rgb: [185, 120, 130], texture: 22 },
  { name: 'Kandla Grey Sandstone', image: '/paving_and_stones/Kandla Grey Sandstone.jpg', price: 41, category: 'Grey', material: 'Sandstone', rgb: [140, 145, 150], texture: 18 },
  { name: 'Mint Fossil Sandstone', image: '/paving_and_stones/Mint Fossil Sandstone.jpg', price: 46, category: 'Green', material: 'Sandstone', rgb: [165, 175, 155], texture: 28 },
  { name: 'Autumn Brown Sandstone', image: '/paving_and_stones/Autumn Brown Sandstone.jpg', price: 43, category: 'Brown', material: 'Sandstone', rgb: [150, 110, 80], texture: 25 },
  { name: 'Rainbow Sandstone', image: '/paving_and_stones/Rainbow Sandstone.jpg', price: 55, category: 'Multicolor', material: 'Sandstone', rgb: [180, 150, 120], texture: 40 },
  { name: 'Raveena Sandstone', image: '/paving_and_stones/Raveena Sandstone.jpg', price: 48, category: 'Multicolor', material: 'Sandstone', rgb: [160, 130, 140], texture: 35 },

  // --- ADDITIONAL GRANITES ---
  { name: 'Vizag Blue Granite', image: '/granite_images/Vizag Blue Granite.webp', price: 58, category: 'Blue', material: 'Granite', rgb: [65, 80, 130], texture: 60 },
  { name: 'Madura Gold Granite', image: '/granite_images/Madura Gold Granite.jpg', price: 60, category: 'Gold', material: 'Granite', rgb: [200, 170, 95], texture: 65 },
  { name: 'Shiva Gold Granite', image: '/granite_images/Shiva Gold Granite.jpg', price: 55, category: 'Gold', material: 'Granite', rgb: [195, 165, 110], texture: 50 },
  { name: 'Kashmir Gold Granite', image: '/granite_images/Kashmir Gold Granite.jpg', price: 56, category: 'Gold', material: 'Granite', rgb: [190, 160, 100], texture: 45 },
  { name: 'Raw Silk Granite', image: '/granite_images/Raw Silk Granite.jpg', price: 52, category: 'Cream', material: 'Granite', rgb: [220, 205, 185], texture: 40 },
  { name: 'Paradiso Granite', image: '/granite_images/Paradiso Granite.jpg', price: 54, category: 'Multicolor', material: 'Granite', rgb: [140, 110, 125], texture: 70 },
  { name: 'Ruby Red Granite', image: '/granite_images/Ruby Red Granite.jpg', price: 65, category: 'Red', material: 'Granite', rgb: [150, 40, 45], texture: 45 },
  { name: 'Rosy Pink Granite', image: '/granite_images/Rosy Pink Granite.webp', price: 48, category: 'Pink', material: 'Granite', rgb: [185, 140, 145], texture: 35 },

  // --- OTHER MATERIALS ---
  { name: 'Calacatta Quartz', image: '/quartz_images/Calacatta Quartz.jpg', price: 70, category: 'White', material: 'Quartz', rgb: [238, 235, 230], texture: 15 },
  { name: 'Sparkling Black Quartz', image: '/quartz_images/Sparkling Black Quartz.jpg', price: 68, category: 'Black', material: 'Quartz', rgb: [25, 25, 35], texture: 60 },
  { name: 'Ceramic White Tile', image: '/other/Ceramic White Tile.jpg', price: 20, category: 'White', material: 'Tiles', rgb: [245, 245, 245], texture: 5 },
  { name: 'Porcelain Blue Tile', image: '/other/Porcelain Blue Tile.jpg', price: 25, category: 'Blue', material: 'Tiles', rgb: [70, 95, 150], texture: 5 },
  { name: 'Yellow Onyx', image: '/onyx_images/Yellow Onyx.jpg', price: 120, category: 'Gold', material: 'Onyx', rgb: [215, 185, 65], texture: 20 },
  { name: 'Green Onyx', image: '/onyx_images/Green Onyx.jpg', price: 130, category: 'Green', material: 'Onyx', rgb: [65, 128, 72], texture: 15 },
  { name: 'Classic White Terrazzo', image: '/other/Classic White Terrazzo.jpg', price: 45, category: 'White', material: 'Terrazzo', rgb: [225, 220, 215], texture: 55 },
  { name: 'Dark Terrazzo', image: '/other/Dark Terrazzo.jpg', price: 48, category: 'Black', material: 'Terrazzo', rgb: [32, 30, 38], texture: 60 },
  { name: 'Macaubas Quartzite', image: '/quartz_images/Macaubas Quartzite.jpg', price: 85, category: 'White', material: 'Quartzite', rgb: [205, 200, 195], texture: 30 },
  { name: 'Azul Macaubas', image: '/other/Azul Macaubas.jpg', price: 110, category: 'Blue', material: 'Quartzite', rgb: [55, 72, 138], texture: 40 },
  { name: 'Black Soapstone', image: '/other/Black Soapstone.jpg', price: 60, category: 'Black', material: 'Soapstone', rgb: [48, 48, 48], texture: 10 },
  { name: 'Green Soapstone', image: '/other/Green Soapstone.jpg', price: 65, category: 'Green', material: 'Soapstone', rgb: [52, 95, 60], texture: 12 },
  { name: 'Basaltina Black', image: '/other/Basaltina Black.jpg', price: 50, category: 'Black', material: 'Basalt', rgb: [28, 28, 28], texture: 8 },
  { name: 'Black Slate', image: '/other/Black Slate.jpg', price: 35, category: 'Black', material: 'Slate', rgb: [40, 40, 38], texture: 20 },
  { name: 'Rusty Slate', image: '/other/Rusty Slate.jpg', price: 38, category: 'Brown', material: 'Slate', rgb: [155, 105, 72], texture: 30 },
  { name: 'Classic Travertine', image: '/other/Classic Travertine.jpg', price: 55, category: 'Gold', material: 'Travertine', rgb: [192, 168, 120], texture: 25 },
  { name: 'Walnut Travertine', image: '/other/Walnut Travertine.jpg', price: 58, category: 'Brown', material: 'Travertine', rgb: [128, 95, 68], texture: 20 },
  { name: 'Crema Limestone', image: '/paving_and_stones/Crema Limestone.jpg', price: 45, category: 'White', material: 'Limestone', rgb: [215, 205, 182], texture: 15 },
  { name: 'Kota Blue Limestone', image: '/paving_and_stones/Kota Blue Limestone.jpg', price: 40, category: 'Blue', material: 'Limestone', rgb: [85, 110, 148], texture: 20 },

  // --- QUARTZ SCRAPED ---
  { name: 'Iced White', image: '/quartz_images/Iced_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac White', image: '/quartz_images/Zodiac_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Costa Maple', image: '/quartz_images/Zodiac_Costa_Maple.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Black', image: '/quartz_images/Zodiac_Black.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Light Red', image: '/quartz_images/Zodiac_Light_Red.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Dark Red', image: '/quartz_images/Zodiac_Dark_Red.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Grey', image: '/quartz_images/Zodiac_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Light Blue', image: '/quartz_images/Zodiac_Light_Blue.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Light Brown', image: '/quartz_images/Zodiac_Light_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Antartica', image: '/quartz_images/Zodiac_Antartica.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Yellow', image: '/quartz_images/Zodiac_Yellow.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Aqua Green', image: '/quartz_images/Zodiac_Aqua_Green.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Sandstone White', image: '/quartz_images/Sandstone_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Sandstone Beige', image: '/quartz_images/Sandstone_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Ginger Tan', image: '/quartz_images/Ginger_Tan.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Stellar Grey', image: '/quartz_images/Stellar_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Jet Black', image: '/quartz_images/Jet_Black.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Cristal White', image: '/quartz_images/Cristal_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Cristal Grey', image: '/quartz_images/Cristal_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Barsha Pearl', image: '/quartz_images/Barsha_Pearl.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Bianco Carrara', image: '/quartz_images/Bianco_Carrara.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Riviera', image: '/quartz_images/Riviera.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Glacier White', image: '/quartz_images/Glacier_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara White', image: '/indian_marble_images/Carrara White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara Blanco', image: '/quartz_images/Carrara_Blanco.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara Dark Night', image: '/quartz_images/Carrara_Dark_Night.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara Cashmere', image: '/quartz_images/Carrara_Cashmere.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Calacatta Classic', image: '/quartz_images/Calacatta_Classic.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Nero Marquina', image: '/quartz_images/Nero_Marquina.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy White', image: '/quartz_images/Galaxy_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Black', image: '/quartz_images/Galaxy_Black.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Grey', image: '/quartz_images/Galaxy_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Mocha Brown', image: '/quartz_images/Galaxy_Mocha_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Toffee Brown', image: '/quartz_images/Galaxy_Toffee_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Beige', image: '/quartz_images/Galaxy_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Derby White', image: '/quartz_images/Derby_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Oxford White', image: '/quartz_images/Oxford_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Lincoln Beige', image: '/quartz_images/Lincoln_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Savoy Beige', image: '/quartz_images/Savoy_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Victorian Brown', image: '/quartz_images/Victorian_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Manchester Brown', image: '/quartz_images/Manchester_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Brentwood Grey', image: '/quartz_images/Brentwood_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Durham Grey', image: '/quartz_images/Durham_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
];

export const Quartz_products = [
  { name: 'Iced White', image: '/quartz_images/Iced_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac White', image: '/quartz_images/Zodiac_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Costa Maple', image: '/quartz_images/Zodiac_Costa_Maple.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Black', image: '/quartz_images/Zodiac_Black.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Light Red', image: '/quartz_images/Zodiac_Light_Red.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Dark Red', image: '/quartz_images/Zodiac_Dark_Red.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Grey', image: '/quartz_images/Zodiac_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Light Blue', image: '/quartz_images/Zodiac_Light_Blue.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Light Brown', image: '/quartz_images/Zodiac_Light_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Antartica', image: '/quartz_images/Zodiac_Antartica.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Yellow', image: '/quartz_images/Zodiac_Yellow.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Zodiac Aqua Green', image: '/quartz_images/Zodiac_Aqua_Green.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Sandstone White', image: '/quartz_images/Sandstone_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Sandstone Beige', image: '/quartz_images/Sandstone_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Ginger Tan', image: '/quartz_images/Ginger_Tan.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Stellar Grey', image: '/quartz_images/Stellar_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Jet Black', image: '/quartz_images/Jet_Black.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Cristal White', image: '/quartz_images/Cristal_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Cristal Grey', image: '/quartz_images/Cristal_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Barsha Pearl', image: '/quartz_images/Barsha_Pearl.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Bianco Carrara', image: '/quartz_images/Bianco_Carrara.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Riviera', image: '/quartz_images/Riviera.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Glacier White', image: '/quartz_images/Glacier_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara White', image: '/indian_marble_images/Carrara White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara Blanco', image: '/quartz_images/Carrara_Blanco.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara Dark Night', image: '/quartz_images/Carrara_Dark_Night.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Carrara Cashmere', image: '/quartz_images/Carrara_Cashmere.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Calacatta Classic', image: '/quartz_images/Calacatta_Classic.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Nero Marquina', image: '/quartz_images/Nero_Marquina.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy White', image: '/quartz_images/Galaxy_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Black', image: '/quartz_images/Galaxy_Black.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Grey', image: '/quartz_images/Galaxy_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Mocha Brown', image: '/quartz_images/Galaxy_Mocha_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Toffee Brown', image: '/quartz_images/Galaxy_Toffee_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Galaxy Beige', image: '/quartz_images/Galaxy_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Derby White', image: '/quartz_images/Derby_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Oxford White', image: '/quartz_images/Oxford_White.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Lincoln Beige', image: '/quartz_images/Lincoln_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Savoy Beige', image: '/quartz_images/Savoy_Beige.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Victorian Brown', image: '/quartz_images/Victorian_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Manchester Brown', image: '/quartz_images/Manchester_Brown.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  { name: 'Brentwood Grey', image: '/quartz_images/Brentwood_Grey.jpg', price: 60, category: 'Quartz', material: 'Quartz', rgb: [230, 230, 230], texture: 15 },
  // Other Natural Stones
  { name: 'Silver Grey Quartzite', image: '/indian_marble_images/silver-grey-color-tumbled-marble-pebbles-stones-low-price-round-rough-unpolished-landscaping-rocks.jpg', price: 65, category: 'Grey', material: 'Quartzite', rgb: [160, 160, 165], texture: 25 },
  { name: 'Deoli Green Quartzite', image: '/paving_and_stones/Raj Green Paving Stones.jpg', price: 70, category: 'Green', material: 'Quartzite', rgb: [95, 115, 95], texture: 35 },
  { name: 'Copper Slate Quartzite', image: '/paving_and_stones/Autumn Brown Paving Stone.jpg', price: 68, category: 'Brown', material: 'Quartzite', rgb: [155, 110, 80], texture: 40 },
  { name: 'Himachal White Quartzite', image: '/indian_marble_images/white-marble-jumbo-size-tumbled-pebbles-multi-purpose-uses-outdoor-decor-pathway-pavement-stones.jpg', price: 75, category: 'White', material: 'Quartzite', rgb: [230, 230, 230], texture: 20 },
  { name: 'Ocean Blue Quartzite', image: '/paving_and_stones/Kota Blue Limestone Paving Stone.jpg', price: 80, category: 'Blue', material: 'Quartzite', rgb: [100, 120, 140], texture: 30 },
  { name: 'Golden Grey Quartzite', image: '/paving_and_stones/yellow-golden-touch-limestone-tumbled-fort-stone-indian-pebbles-poolside-decorative-material.jpg', price: 68, category: 'Yellow', material: 'Quartzite', rgb: [195, 175, 110], texture: 25 },
  { name: 'Kota Blue Limestone', image: '/paving_and_stones/Kota Blue Limestone.jpg', price: 45, category: 'Blue', material: 'Limestone', rgb: [110, 130, 145], texture: 15 },
  { name: 'Tandur Yellow Limestone', image: '/paving_and_stones/yellow-golden-touch-limestone-tumbled-fort-stone-indian-pebbles-poolside-decorative-material.jpg', price: 50, category: 'Yellow', material: 'Limestone', rgb: [210, 190, 130], texture: 20 },
  { name: 'Kadapa Black Limestone', image: '/paving_and_stones/Kota Black Limestone Paving Stone.jpg', price: 55, category: 'Black', material: 'Limestone', rgb: [35, 38, 40], texture: 15 },
  { name: 'Lime Peacock Limestone', image: '/paving_and_stones/Crema Limestone.jpg', price: 60, category: 'Multicolor', material: 'Limestone', rgb: [180, 175, 160], texture: 30 },
  { name: 'Jaisalmer Yellow Limestone', image: '/indian_marble_images/jaisalmer-Yellow-marble-300x249.png', price: 65, category: 'Yellow', material: 'Limestone', rgb: [225, 195, 95], texture: 15 },
  { name: 'Shahabad Grey Limestone', image: '/paving_and_stones/Kandla Grey Sandstone.jpg', price: 48, category: 'Grey', material: 'Limestone', rgb: [145, 150, 155], texture: 15 },
  { name: 'Jack Black Slate', image: '/paving_and_stones/black-polished-tumbled-agate-ornamental-stones-garden-pavement-nursery-decorative-pebbles.jpg', price: 55, category: 'Black', material: 'Slate', rgb: [30, 32, 35], texture: 35 },
  { name: 'Kund Multicolor Slate', image: '/paving_and_stones/rainbow-sandstone-dry-tumbled-unpolished-natural-pebbles-fountain-garden-home-decor-stone.jpg', price: 60, category: 'Multicolor', material: 'Slate', rgb: [165, 125, 95], texture: 45 },
  { name: 'Silver Shine Slate', image: '/paving_and_stones/Kandla Grey Paving Stone.jpg', price: 58, category: 'Grey', material: 'Slate', rgb: [165, 170, 175], texture: 30 },
  { name: 'Copper Slate', image: '/paving_and_stones/Autumn Brown Paving Stone.jpg', price: 55, category: 'Brown', material: 'Slate', rgb: [140, 95, 65], texture: 35 },
  { name: 'Ocean Green Slate', image: '/paving_and_stones/Raj Green Paving Stones.jpg', price: 62, category: 'Green', material: 'Slate', rgb: [85, 110, 95], texture: 40 },
  { name: 'Rustic Gold Slate', image: '/paving_and_stones/yellow-golden-touch-limestone-tumbled-fort-stone-indian-pebbles-poolside-decorative-material.jpg', price: 58, category: 'Yellow', material: 'Slate', rgb: [185, 160, 100], texture: 35 },
  { name: 'Absolute Black Basalt', image: '/paving_and_stones/black-basalt-natural-pebbles-garden-home-nature-landscape-driveway-pathway-stones.jpg', price: 70, category: 'Black', material: 'Basalt', rgb: [25, 25, 28], texture: 10 },
  { name: 'Grey Volcanic Basalt', image: '/paving_and_stones/lava-stone-natural-pond-landscaping-river-decorative-indoor-outdoor-garden-marine-products.jpg', price: 72, category: 'Grey', material: 'Basalt', rgb: [95, 100, 105], texture: 25 },
  { name: 'Charcoal Basalt', image: '/paving_and_stones/black-polished-tumbled-agate-ornamental-stones-garden-pavement-nursery-decorative-pebbles.jpg', price: 68, category: 'Black', material: 'Basalt', rgb: [40, 42, 45], texture: 15 },
  { name: 'Honed Black Basalt', image: '/paving_and_stones/black-basalt-natural-pebbles-garden-home-nature-landscape-driveway-pathway-stones.jpg', price: 75, category: 'Black', material: 'Basalt', rgb: [22, 22, 25], texture: 10 },
  { name: 'Textured Outdoor Basalt', image: '/paving_and_stones/Kandla Grey Paving Stone.jpg', price: 68, category: 'Grey', material: 'Basalt', rgb: [130, 135, 140], texture: 30 },
  { name: 'Kota Blue Stone', image: '/paving_and_stones/Kota Blue Limestone.jpg', price: 42, category: 'Blue', material: 'Limestone', rgb: [105, 125, 140], texture: 10 },
  { name: 'Kota Brown Stone', image: '/paving_and_stones/Kota Brown Paving Stone.jpg', price: 42, category: 'Brown', material: 'Limestone', rgb: [145, 115, 90], texture: 10 },
  { name: 'Kota Grey Polished', image: '/indian_marble_images/Kota stone.png', price: 46, category: 'Grey', material: 'Limestone', rgb: [140, 145, 150], texture: 10 },
  { name: 'Kota Green Rough', image: '/paving_and_stones/Raj Green Paving Stones.jpg', price: 45, category: 'Green', material: 'Limestone', rgb: [95, 115, 100], texture: 20 },
  { name: 'Roman Silver Travertine', image: '/paving_and_stones/Travertine.png', price: 85, category: 'Grey', material: 'Travertine', rgb: [175, 170, 165], texture: 30 },
  { name: 'Classic Beige Travertine', image: '/paving_and_stones/Dholpur Beige Sandstone.jpg', price: 80, category: 'Beige', material: 'Travertine', rgb: [215, 205, 185], texture: 25 },
  { name: 'Noce Walnut Travertine', image: '/paving_and_stones/Autumn Brown Sandstone.jpg', price: 82, category: 'Brown', material: 'Travertine', rgb: [155, 125, 95], texture: 30 },

  // Royal Gem Stones
  { name: 'Indian Blue Agate', image: '/gemstones/agate/indianblueagate.jpg', price: 280, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [70, 130, 180], texture: 80 },
  { name: 'Black Agate Luxury Surface', image: '/gemstones/agate/blackagate.jpg', price: 290, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [25, 25, 30], texture: 75 },
  { name: 'Mix Agate Gemstone', image: '/gemstones/agate/mixagate.jpg', price: 310, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [180, 140, 100], texture: 85 },
  { name: 'Crystal Agate Slab', image: '/gemstones/agate/crystalagate.jpg', price: 320, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [230, 230, 235], texture: 70 },
  { name: 'Moss Agate Surface', image: '/gemstones/agate/mossagate.jpg', price: 295, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [85, 115, 90], texture: 80 },
  { name: 'Yellow Agate Gemstone', image: '/gemstones/agate/yellowagate.jpg', price: 285, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [235, 195, 75], texture: 75 },
  { name: 'Rose Quartz Gemstone', image: '/gemstones/quartz/rosequartz.jpg', price: 350, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [245, 195, 205], texture: 65 },
  { name: 'Smokey Quartz Slab', image: '/gemstones/quartz/smokeyquartz.jpg', price: 340, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [115, 95, 85], texture: 70 },
  { name: 'Amethyst Luxury Gemstone', image: '/gemstones/quartz/amethyst.jpg', price: 420, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [155, 90, 180], texture: 85 },
  { name: 'Golden Quartz Surface', image: '/gemstones/quartz/goldenquartz.jpg', price: 380, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [215, 175, 85], texture: 75 },
  { name: 'Green Fluorite Slab', image: '/gemstones/quartz/greenfluorite.jpg', price: 360, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [85, 185, 145], texture: 80 },
  { name: 'Tiger Eye Gemstone Slab', image: '/gemstones/gemstone/tigereye.jpg', price: 450, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [185, 125, 45], texture: 90 },
  { name: 'Lapis Lazuli Luxury Slab', image: '/gemstones/gemstone/lapizlazuli.jpg', price: 480, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [35, 65, 155], texture: 85 },
  { name: 'Malachite Flower Gemstone', image: '/gemstones/gemstone/malachiteflower.jpg', price: 520, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [25, 135, 85], texture: 95 },
  { name: 'Labradorite Luxury Slab', image: '/gemstones/gemstone/labrodorite.jpg', price: 490, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [65, 85, 105], texture: 90 },
  { name: 'Sodalite Blue Surface', image: '/gemstones/gemstone/sodaliteblue.jpg', price: 440, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [45, 75, 140], texture: 85 },
  { name: 'Amazonite Gemstone Slab', image: '/gemstones/gemstone/amazonite.jpg', price: 460, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [95, 205, 175], texture: 80 },
  { name: 'Golden Mother of Pearl', image: '/gemstones/shellstone/goldenmop.jpg', price: 550, category: 'Royal Gemstone', material: 'Shellstone', isRoyalGemStone: true, rgb: [235, 205, 145], texture: 70 },
  { name: 'Petrified Wood Fossil Slab', image: '/gemstones/fossil/petrifiedwood.jpg', price: 480, category: 'Royal Gemstone', material: 'Fossil', isRoyalGemStone: true, rgb: [135, 95, 65], texture: 85 },
  { name: 'Red Jasper Gemstone Surface', image: '/gemstones/jasper/redjasper.jpg', price: 410, category: 'Royal Gemstone', material: 'Jasper', isRoyalGemStone: true, rgb: [165, 55, 45], texture: 80 }
];

export const Onyx_products = [
  { name: 'Orange Ice Onyx', image: '/onyx_images/Orange_Ice_Onyx.jpg', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 165, 0], texture: 10 },
  { name: 'Blue Ice Onyx', image: '/onyx_images/Blue_Ice_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [0, 0, 255], texture: 10 },
  { name: 'Green Ice Onyx', image: '/onyx_images/Green_Ice_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [0, 255, 0], texture: 10 },
  { name: 'Pink Ice Onyx', image: '/onyx_images/Pink_Ice_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 192, 203], texture: 10 },
  { name: 'Tiger Onyx', image: '/onyx_images/Tiger_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 204, 0], texture: 10 },
  { name: 'Wooden Onyx', image: '/onyx_images/Wooden_Onyx.jpg', price: 120, category: 'Onyx', material: 'Onyx', rgb: [139, 69, 19], texture: 10 },
  { name: 'White Onyx Gemstone', image: '/onyx_images/White_Onyx_Gemstone.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 255, 255], texture: 10 },
  { name: 'Honey Onyx', image: '/onyx_images/Honey_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 204, 0], texture: 10 },
  { name: 'Green Onyx', image: '/onyx_images/Green Onyx.jpg', price: 120, category: 'Onyx', material: 'Onyx', rgb: [0, 128, 0], texture: 10 },
  { name: 'Bubble Onyx', image: '/onyx_images/Bubble_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 255, 255], texture: 10 },
  { name: 'Cappuccino Onyx', image: '/onyx_images/Cappuccino_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [210, 180, 140], texture: 10 },
  { name: 'Velluto Onyx', image: '/onyx_images/Velluto_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [222, 184, 135], texture: 10 },
  { name: 'Silver Onyx', image: '/onyx_images/Silver_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [192, 192, 192], texture: 10 },
  { name: 'Gold Onyx', image: '/onyx_images/Gold_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 215, 0], texture: 10 },
  { name: 'Coca Cola Onyx', image: '/onyx_images/Coca_Cola_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [139, 69, 19], texture: 10 },
  { name: 'Satin Onyx', image: '/onyx_images/Satin_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [245, 245, 245], texture: 10 },
  { name: 'Salmon Onyx', image: '/onyx_images/Salmon_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [250, 128, 114], texture: 10 },
  { name: 'White Onyx', image: '/onyx_images/White_Onyx.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [255, 255, 255], texture: 10 },
  { name: 'Dark Desert Rose', image: '/onyx_images/Dark_Desert_Rose.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [165, 42, 42], texture: 10 },
  { name: 'Light Desert Rose', image: '/onyx_images/Light_Desert_Rose.png', price: 120, category: 'Onyx', material: 'Onyx', rgb: [205, 92, 92], texture: 10 }
];

export const OTHER_NATURAL_STONES = [
  // Quartzite
  { name: 'Silver Grey Quartzite', image: '/indian_marble_images/silver-grey-color-tumbled-marble-pebbles-stones-low-price-round-rough-unpolished-landscaping-rocks.jpg', price: 65, category: 'Grey', type: 'Quartzite', material: 'Quartzite' },
  { name: 'Deoli Green Quartzite', image: '/paving_and_stones/Raj Green Paving Stones.jpg', price: 70, category: 'Green', type: 'Quartzite', material: 'Quartzite' },
  { name: 'Copper Slate Quartzite', image: '/paving_and_stones/Autumn Brown Paving Stone.jpg', price: 68, category: 'Brown', type: 'Quartzite', material: 'Quartzite' },
  { name: 'Himachal White Quartzite', image: '/indian_marble_images/white-marble-jumbo-size-tumbled-pebbles-multi-purpose-uses-outdoor-decor-pathway-pavement-stones.jpg', price: 75, category: 'White', type: 'Quartzite', material: 'Quartzite' },
  { name: 'Ocean Blue Quartzite', image: '/paving_and_stones/Kota Blue Limestone Paving Stone.jpg', price: 80, category: 'Blue', type: 'Quartzite', material: 'Quartzite' },
  { name: 'Golden Grey Quartzite', image: '/paving_and_stones/yellow-golden-touch-limestone-tumbled-fort-stone-indian-pebbles-poolside-decorative-material.jpg', price: 68, category: 'Yellow', type: 'Quartzite', material: 'Quartzite' },

  // Limestone
  { name: 'Kota Blue Limestone', image: '/paving_and_stones/Kota Blue Limestone.jpg', price: 45, category: 'Blue', type: 'Limestone', material: 'Limestone' },
  { name: 'Tandur Yellow Limestone', image: '/paving_and_stones/yellow-golden-touch-limestone-tumbled-fort-stone-indian-pebbles-poolside-decorative-material.jpg', price: 50, category: 'Yellow', type: 'Limestone', material: 'Limestone' },
  { name: 'Kadapa Black Limestone', image: '/paving_and_stones/Kota Black Limestone Paving Stone.jpg', price: 55, category: 'Black', type: 'Limestone', material: 'Limestone' },
  { name: 'Lime Peacock Limestone', image: '/paving_and_stones/Crema Limestone.jpg', price: 60, category: 'Multicolor', type: 'Limestone', material: 'Limestone' },
  { name: 'Jaisalmer Yellow Limestone', image: '/indian_marble_images/jaisalmer-Yellow-marble-300x249.png', price: 65, category: 'Yellow', type: 'Limestone', material: 'Limestone' },
  { name: 'Shahabad Grey Limestone', image: '/paving_and_stones/Kandla Grey Sandstone.jpg', price: 48, category: 'Grey', type: 'Limestone', material: 'Limestone' },

  // Slate Stone
  { name: 'Jack Black Slate', image: '/paving_and_stones/black-polished-tumbled-agate-ornamental-stones-garden-pavement-nursery-decorative-pebbles.jpg', price: 55, category: 'Black', type: 'Slate Stone', material: 'Slate' },
  { name: 'Kund Multicolor Slate', image: '/paving_and_stones/rainbow-sandstone-dry-tumbled-unpolished-natural-pebbles-fountain-garden-home-decor-stone.jpg', price: 60, category: 'Multicolor', type: 'Slate Stone', material: 'Slate' },
  { name: 'Silver Shine Slate', image: '/paving_and_stones/Kandla Grey Paving Stone.jpg', price: 58, category: 'Grey', type: 'Slate Stone', material: 'Slate' },
  { name: 'Copper Slate', image: '/paving_and_stones/Autumn Brown Paving Stone.jpg', price: 55, category: 'Brown', type: 'Slate Stone', material: 'Slate' },
  { name: 'Ocean Green Slate', image: '/paving_and_stones/Raj Green Paving Stones.jpg', price: 62, category: 'Green', type: 'Slate Stone', material: 'Slate' },
  { name: 'Rustic Gold Slate', image: '/paving_and_stones/yellow-golden-touch-limestone-tumbled-fort-stone-indian-pebbles-poolside-decorative-material.jpg', price: 58, category: 'Yellow', type: 'Slate Stone', material: 'Slate' },

  // Basalt
  { name: 'Absolute Black Basalt', image: '/paving_and_stones/black-basalt-natural-pebbles-garden-home-nature-landscape-driveway-pathway-stones.jpg', price: 70, category: 'Black', type: 'Basalt', material: 'Basalt' },
  { name: 'Grey Volcanic Basalt', image: '/paving_and_stones/lava-stone-natural-pond-landscaping-river-decorative-indoor-outdoor-garden-marine-products.jpg', price: 72, category: 'Grey', type: 'Basalt', material: 'Basalt' },
  { name: 'Charcoal Basalt', image: '/paving_and_stones/black-polished-tumbled-agate-ornamental-stones-garden-pavement-nursery-decorative-pebbles.jpg', price: 68, category: 'Black', type: 'Basalt', material: 'Basalt' },
  { name: 'Honed Black Basalt', image: '/paving_and_stones/black-basalt-natural-pebbles-garden-home-nature-landscape-driveway-pathway-stones.jpg', price: 75, category: 'Black', type: 'Basalt', material: 'Basalt' },
  { name: 'Textured Outdoor Basalt', image: '/paving_and_stones/Kandla Grey Paving Stone.jpg', price: 68, category: 'Grey', type: 'Basalt', material: 'Basalt' },

  // Kota Stone
  { name: 'Kota Blue Stone', image: '/paving_and_stones/Kota Blue Limestone.jpg', price: 42, category: 'Blue', type: 'Kota Stone', material: 'Limestone' },
  { name: 'Kota Brown Stone', image: '/paving_and_stones/Kota Brown Paving Stone.jpg', price: 42, category: 'Brown', type: 'Kota Stone', material: 'Limestone' },
  { name: 'Kota Grey Polished', image: '/indian_marble_images/Kota stone.png', price: 46, category: 'Grey', type: 'Kota Stone', material: 'Limestone' },
  { name: 'Kota Green Rough', image: '/paving_and_stones/Raj Green Paving Stones.jpg', price: 45, category: 'Green', type: 'Kota Stone', material: 'Limestone' },

  // Travertine
  { name: 'Roman Silver Travertine', image: '/paving_and_stones/Travertine.png', price: 85, category: 'Grey', type: 'Travertine', material: 'Travertine' },
  { name: 'Classic Beige Travertine', image: '/paving_and_stones/Dholpur Beige Sandstone.jpg', price: 80, category: 'Beige', type: 'Travertine', material: 'Travertine' },
  { name: 'Noce Walnut Travertine', image: '/paving_and_stones/Autumn Brown Sandstone.jpg', price: 82, category: 'Brown', type: 'Travertine', material: 'Travertine' }
];

export const ROYAL_GEM_STONE_PRODUCTS = [
  // Agate
  { name: 'Indian Blue Agate', image: '/gemstones/agate/indianblueagate.jpg', price: 280, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [70, 130, 180], texture: 80 },
  { name: 'Black Agate Luxury Surface', image: '/gemstones/agate/blackagate.jpg', price: 290, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [25, 25, 30], texture: 75 },
  { name: 'Mix Agate Gemstone', image: '/gemstones/agate/mixagate.jpg', price: 310, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [180, 140, 100], texture: 85 },
  { name: 'Crystal Agate Slab', image: '/gemstones/agate/crystalagate.jpg', price: 320, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [230, 230, 235], texture: 70 },
  { name: 'Moss Agate Surface', image: '/gemstones/agate/mossagate.jpg', price: 295, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [85, 115, 90], texture: 80 },
  { name: 'Yellow Agate Gemstone', image: '/gemstones/agate/yellowagate.jpg', price: 285, category: 'Royal Gemstone', material: 'Agate', isRoyalGemStone: true, rgb: [235, 195, 75], texture: 75 },

  // Quartz
  { name: 'Rose Quartz Gemstone', image: '/gemstones/quartz/rosequartz.jpg', price: 350, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [245, 195, 205], texture: 65 },
  { name: 'Smokey Quartz Slab', image: '/gemstones/quartz/smokeyquartz.jpg', price: 340, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [115, 95, 85], texture: 70 },
  { name: 'Amethyst Luxury Gemstone', image: '/gemstones/quartz/amethyst.jpg', price: 420, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [155, 90, 180], texture: 85 },
  { name: 'Golden Quartz Surface', image: '/gemstones/quartz/goldenquartz.jpg', price: 380, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [215, 175, 85], texture: 75 },
  { name: 'Green Fluorite Slab', image: '/gemstones/quartz/greenfluorite.jpg', price: 360, category: 'Royal Gemstone', material: 'Quartz', isRoyalGemStone: true, rgb: [85, 185, 145], texture: 80 },

  // Exotic Gemstones
  { name: 'Tiger Eye Gemstone Slab', image: '/gemstones/gemstone/tigereye.jpg', price: 450, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [185, 125, 45], texture: 90 },
  { name: 'Lapis Lazuli Luxury Slab', image: '/gemstones/gemstone/lapizlazuli.jpg', price: 480, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [35, 65, 155], texture: 85 },
  { name: 'Malachite Flower Gemstone', image: '/gemstones/gemstone/malachiteflower.jpg', price: 520, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [25, 135, 85], texture: 95 },
  { name: 'Labradorite Luxury Slab', image: '/gemstones/gemstone/labrodorite.jpg', price: 490, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [65, 85, 105], texture: 90 },
  { name: 'Sodalite Blue Surface', image: '/gemstones/gemstone/sodaliteblue.jpg', price: 440, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [45, 75, 140], texture: 85 },
  { name: 'Amazonite Gemstone Slab', image: '/gemstones/gemstone/amazonite.jpg', price: 460, category: 'Royal Gemstone', material: 'Gemstone', isRoyalGemStone: true, rgb: [95, 205, 175], texture: 80 },

  // Shellstone & Fossil & Jasper
  { name: 'Golden Mother of Pearl', image: '/gemstones/shellstone/goldenmop.jpg', price: 550, category: 'Royal Gemstone', material: 'Shellstone', isRoyalGemStone: true, rgb: [235, 205, 145], texture: 70 },
  { name: 'Petrified Wood Fossil Slab', image: '/gemstones/fossil/petrifiedwood.jpg', price: 480, category: 'Royal Gemstone', material: 'Fossil', isRoyalGemStone: true, rgb: [135, 95, 65], texture: 85 },
  { name: 'Red Jasper Gemstone Surface', image: '/gemstones/jasper/redjasper.jpg', price: 410, category: 'Royal Gemstone', material: 'Jasper', isRoyalGemStone: true, rgb: [165, 55, 45], texture: 80 }
];
